### ISSUE TITLE
Erro ao abrir o finding_donors_PT.ipynb pelo try.jupyter.org

### ISSUE THREAD

**Issue by pattrickmiller** [udacity/br-machine-learning#6]
******** UPDATE **********

O erro era meu, pois foi na forma que eu fiz o download do arquivo do git. Clicando no link e usando o "Save as".

-----------------------------

Estou recebendo a mensagem de erro 

![capturar](https://user-images.githubusercontent.com/10373863/38432542-29a8508a-399e-11e8-9b7d-32968d1f39fc.PNG)

Quando abro o arquivo no textpad parece que tem apenas tags html.

**Comment by prietoab** [comment]
@pattrickmiller, você conseguiu resolver seu problema?

Tentei um caminho alternativo mas, infelizmente, estou tendo um problema semelhante.

Salvei o notebook em um diretório no Linux:

![image](https://user-images.githubusercontent.com/13477656/40341243-60a96864-5d5a-11e8-90e2-a2ea22349028.png)

 e, usando o terminal, nesse diretório, "subi" o Jupyter Notebook:

![image](https://user-images.githubusercontent.com/13477656/40341263-83f67c44-5d5a-11e8-891d-25bf0b21e34c.png)

Mas, quando tento acessar o Notebook o erro abaixo acontece:

![image](https://user-images.githubusercontent.com/13477656/40341276-951693c4-5d5a-11e8-977d-fcc9ce029ef5.png)

:-(

**Comment by pattrickmiller** [comment]
Bom dia,

sim,

no meu caso, foi porque fiz o download do arquivo  finding_donors_PT.ipynb
direto github e o mesmo veio em formato html (quando você abre o arquivo o
github converte para exibição).

Neste caso, tem que clicar na opção raw do github.

[image: image.png]

E em seguida salvar como

[image: image.png]

**Comment by rriccilopes** [comment]
@prietoab isso. Ou faz clone do repositório (ou [download](https://github.com/udacity/br-machine-learning/archive/master.zip)). Se você já estiver fazendo isso, me informe!
