### ISSUE TITLE
Erro ao abrir o finding_donors_PT.ipynb no Jupyter Notebook (Ubuntu, Anaconda, Python 3)

### ISSUE THREAD

**Issue by prietoab** [udacity/br-machine-learning#7]
## Baxei os arquivos do projeto em um diretório no Ubuntu e abri o Jupyter Notebook normalmente:

![image](https://user-images.githubusercontent.com/13477656/40341370-2fa3739e-5d5b-11e8-9e8e-212e41ed376c.png)

## Porém, quando clico no finding_donors_PT.ipynb o seguinte erro acontece:

![image](https://user-images.githubusercontent.com/13477656/40341400-5d259b6c-5d5b-11e8-9846-e0b37233a34a.png)

## (Isso também acontece com a versão original em inglês)

**Comment by rriccilopes** [comment]
@prietoab Tenta fazer clone do repositório (ou [download](https://github.com/udacity/br-machine-learning/archive/master.zip)). Se você já estiver fazendo isso, me informe!
