### ISSUE TITLE
Ajuste pt-br https://github.com/udacity/br-machine-learning/blob/master/projects/finding_donors/finding_donors_PT.ipynb

### ISSUE THREAD

**Issue by gustavojordan** [udacity/br-machine-learning#8]
@rriccilopes  em https://github.com/udacity/br-machine-learning/blob/master/projects/finding_donors/finding_donors_PT.ipynb a frase "Parece uqe utilizar acurácia (accuracy) como uma métrica para avaliar a performance de um modelo é um parâmetro adequado" a palavra "ueq" esta incorreta.

**Comment by rriccilopes** [comment]
@gustavojordan  você não quer fazer a correção e dar um push?
